# Generated by Django 3.2.11 on 2022-04-07 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Алгоритм/подход',
                'verbose_name_plural': 'Алгоритм/подход',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Название слоя в GeoServer')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('zoom_level', models.FloatField(blank=True, null=True, verbose_name='Уровень Zoomа')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='FarmLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Название слоя в GeoServer')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('zoom_level', models.FloatField(blank=True, null=True, verbose_name='Уровень Zoomа')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.district', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Сельхоз угодье',
                'verbose_name_plural': 'Сельхоз угодья',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Название слоя в GeoServer')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('zoom_level', models.FloatField(blank=True, null=True, verbose_name='Уровень Zoomа')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('farm_land', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.farmland', verbose_name='Сельхоз угодье')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
            },
        ),
        migrations.CreateModel(
            name='IndexChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_final', models.BooleanField(default=False, verbose_name='Финальный тип?')),
            ],
            options={
                'verbose_name': 'Индекс/Канал',
                'verbose_name_plural': 'Индексы/Каналы',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Название слоя в GeoServer')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('zoom_level', models.FloatField(blank=True, null=True, verbose_name='Уровень Zoomа')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
            },
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Спутник',
                'verbose_name_plural': 'Спутники',
            },
        ),
        migrations.CreateModel(
            name='RawLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Название слоя в GeoServer')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('zoom_level', models.FloatField(blank=True, null=True, verbose_name='Уровень Zoomа')),
                ('datetime_start', models.DateTimeField(verbose_name='Дата начала съёмки')),
                ('datetime_end', models.DateTimeField(verbose_name='Дата конца съёмки')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.district', verbose_name='Район')),
                ('farm_land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.farmland', verbose_name='Сельхоз угодье')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.field', verbose_name='Поле')),
                ('index_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.indexchannel', verbose_name='Индекс/Канал')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.region', verbose_name='Область')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.satellite', verbose_name='Спутник')),
            ],
            options={
                'verbose_name': 'Исходный слой',
                'verbose_name_plural': 'Исходные слои',
            },
        ),
        migrations.CreateModel(
            name='ProcessedLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Название слоя в GeoServer')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('zoom_level', models.FloatField(blank=True, null=True, verbose_name='Уровень Zoomа')),
                ('datetime_start', models.DateTimeField(verbose_name='Дата начала съёмки')),
                ('datetime_end', models.DateTimeField(verbose_name='Дата конца съёмки')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.algorithm', verbose_name='Алгоритм/подход')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.author', verbose_name='Автор')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.district', verbose_name='Район')),
                ('farm_land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.farmland', verbose_name='Сельхоз угодье')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.field', verbose_name='Поле')),
                ('index_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.indexchannel', verbose_name='Индекс/Канал')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.region', verbose_name='Область')),
                ('source_layers', models.ManyToManyField(to='mainapp.RawLayer', verbose_name='Исходные слои')),
            ],
            options={
                'verbose_name': 'Обработанный слой',
                'verbose_name_plural': 'Обработанные слои',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.region', verbose_name='Область'),
        ),
    ]
