# Generated by Django 3.2.11 on 2022-05-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='mainapp.region', verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='farmland',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farmlands', to='mainapp.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='field',
            name='farm_land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='mainapp.farmland', verbose_name='Сельхоз угодье'),
        ),
        migrations.AlterField(
            model_name='processedlayer',
            name='algorithm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.algorithm', verbose_name='Алгоритм/подход'),
        ),
        migrations.AlterField(
            model_name='processedlayer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='processedlayer',
            name='datetime_end',
            field=models.DateTimeField(null=True, verbose_name='Дата конца съёмки'),
        ),
        migrations.AlterField(
            model_name='processedlayer',
            name='datetime_start',
            field=models.DateTimeField(null=True, verbose_name='Дата начала съёмки'),
        ),
        migrations.AlterField(
            model_name='processedlayer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='district_processed', to='mainapp.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='processedlayer',
            name='farm_land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farm_land_processed', to='mainapp.farmland', verbose_name='Сельхоз угодье'),
        ),
        migrations.AlterField(
            model_name='processedlayer',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_processed', to='mainapp.field', verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='processedlayer',
            name='index_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.indexchannel', verbose_name='Индекс/Канал'),
        ),
        migrations.AlterField(
            model_name='processedlayer',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='region_processed', to='mainapp.region', verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='processedlayer',
            name='source_layers',
            field=models.ManyToManyField(blank=True, to='mainapp.RawLayer', verbose_name='Исходные слои'),
        ),
        migrations.AlterField(
            model_name='rawlayer',
            name='datetime_end',
            field=models.DateTimeField(null=True, verbose_name='Дата конца съёмки'),
        ),
        migrations.AlterField(
            model_name='rawlayer',
            name='datetime_start',
            field=models.DateTimeField(null=True, verbose_name='Дата начала съёмки'),
        ),
        migrations.AlterField(
            model_name='rawlayer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='district_raws', to='mainapp.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='rawlayer',
            name='farm_land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farm_land_raws', to='mainapp.farmland', verbose_name='Сельхоз угодье'),
        ),
        migrations.AlterField(
            model_name='rawlayer',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_raws', to='mainapp.field', verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='rawlayer',
            name='index_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.indexchannel', verbose_name='Индекс/Канал'),
        ),
        migrations.AlterField(
            model_name='rawlayer',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='region_raws', to='mainapp.region', verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='rawlayer',
            name='satellite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.satellite', verbose_name='Спутник'),
        ),
    ]
