# Generated by Django 3.2.11 on 2022-07-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20220519_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Включено?'),
        ),
        migrations.AddField(
            model_name='farmland',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Включено?'),
        ),
        migrations.AddField(
            model_name='field',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Включено?'),
        ),
        migrations.AddField(
            model_name='processedlayer',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Включено?'),
        ),
        migrations.AddField(
            model_name='rawlayer',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Включено?'),
        ),
        migrations.AddField(
            model_name='region',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Включено?'),
        ),
    ]
