# Generated by Django 3.2.11 on 2022-08-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20220718_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='cql_filter',
            field=models.CharField(blank=True, max_length=15000, null=True, unique=True, verbose_name='CQL фильтр'),
        ),
        migrations.AddField(
            model_name='farmland',
            name='cql_filter',
            field=models.CharField(blank=True, max_length=15000, null=True, unique=True, verbose_name='CQL фильтр'),
        ),
        migrations.AddField(
            model_name='field',
            name='cql_filter',
            field=models.CharField(blank=True, max_length=15000, null=True, unique=True, verbose_name='CQL фильтр'),
        ),
        migrations.AddField(
            model_name='processedlayer',
            name='cql_filter',
            field=models.CharField(blank=True, max_length=15000, null=True, unique=True, verbose_name='CQL фильтр'),
        ),
        migrations.AddField(
            model_name='rawlayer',
            name='cql_filter',
            field=models.CharField(blank=True, max_length=15000, null=True, unique=True, verbose_name='CQL фильтр'),
        ),
        migrations.AddField(
            model_name='region',
            name='cql_filter',
            field=models.CharField(blank=True, max_length=15000, null=True, unique=True, verbose_name='CQL фильтр'),
        ),
        migrations.AlterField(
            model_name='processedlayer',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата конца съёмки'),
        ),
        migrations.AlterField(
            model_name='processedlayer',
            name='datetime_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала съёмки'),
        ),
        migrations.AlterField(
            model_name='rawlayer',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата конца съёмки'),
        ),
        migrations.AlterField(
            model_name='rawlayer',
            name='datetime_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала съёмки'),
        ),
    ]
