# Generated by Django 3.2.11 on 2022-10-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20220820_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='cql_filter',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='CQL фильтр'),
        ),
        migrations.AlterField(
            model_name='district',
            name='layer_name',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='Название слоя в GeoServer'),
        ),
        migrations.AlterField(
            model_name='farmland',
            name='cql_filter',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='CQL фильтр'),
        ),
        migrations.AlterField(
            model_name='farmland',
            name='layer_name',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='Название слоя в GeoServer'),
        ),
        migrations.AlterField(
            model_name='field',
            name='cql_filter',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='CQL фильтр'),
        ),
        migrations.AlterField(
            model_name='field',
            name='layer_name',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='Название слоя в GeoServer'),
        ),
        migrations.AlterField(
            model_name='processedlayer',
            name='cql_filter',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='CQL фильтр'),
        ),
        migrations.AlterField(
            model_name='processedlayer',
            name='layer_name',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='Название слоя в GeoServer'),
        ),
        migrations.AlterField(
            model_name='rawlayer',
            name='cql_filter',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='CQL фильтр'),
        ),
        migrations.AlterField(
            model_name='rawlayer',
            name='layer_name',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='Название слоя в GeoServer'),
        ),
        migrations.AlterField(
            model_name='region',
            name='cql_filter',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='CQL фильтр'),
        ),
        migrations.AlterField(
            model_name='region',
            name='layer_name',
            field=models.CharField(blank=True, max_length=15000, null=True, verbose_name='Название слоя в GeoServer'),
        ),
    ]
