# Generated by Django 3.2.11 on 2022-11-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20221026_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='farmland',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='farmland',
            unique_together={('name', 'district')},
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('name', 'farm_land')},
        ),
    ]
