# Generated by Django 3.2.11 on 2022-12-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20221107_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('color_1', models.CharField(blank=True, max_length=10, null=True)),
                ('description_1', models.CharField(blank=True, max_length=50, null=True)),
                ('color_2', models.CharField(blank=True, max_length=10, null=True)),
                ('description_2', models.CharField(blank=True, max_length=50, null=True)),
                ('color_3', models.CharField(blank=True, max_length=10, null=True)),
                ('description_3', models.CharField(blank=True, max_length=50, null=True)),
                ('color_4', models.CharField(blank=True, max_length=10, null=True)),
                ('description_4', models.CharField(blank=True, max_length=50, null=True)),
                ('color_5', models.CharField(blank=True, max_length=10, null=True)),
                ('description_5', models.CharField(blank=True, max_length=50, null=True)),
                ('color_6', models.CharField(blank=True, max_length=10, null=True)),
                ('description_6', models.CharField(blank=True, max_length=50, null=True)),
                ('color_7', models.CharField(blank=True, max_length=10, null=True)),
                ('description_7', models.CharField(blank=True, max_length=50, null=True)),
                ('color_8', models.CharField(blank=True, max_length=10, null=True)),
                ('description_8', models.CharField(blank=True, max_length=50, null=True)),
                ('color_9', models.CharField(blank=True, max_length=10, null=True)),
                ('description_9', models.CharField(blank=True, max_length=50, null=True)),
                ('color_10', models.CharField(blank=True, max_length=10, null=True)),
                ('description_10', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Легенда',
                'verbose_name_plural': 'Легенды',
            },
        ),
    ]
