# Generated by Django 3.2.11 on 2022-12-29 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedlayer',
            name='legend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.legend', verbose_name='Легенда'),
        ),
        migrations.AddField(
            model_name='rawlayer',
            name='legend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.legend', verbose_name='Легенда'),
        ),
    ]
