# Generated by Django 3.2.11 on 2023-01-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20221229_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedlayer',
            name='custom_name',
            field=models.TextField(blank=True, null=True, verbose_name='Особое название'),
        ),
        migrations.AddField(
            model_name='rawlayer',
            name='custom_name',
            field=models.TextField(blank=True, null=True, verbose_name='Особое название'),
        ),
    ]
