# Generated by Django 3.2.11 on 2023-08-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20230106_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedlayer',
            name='legend_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение легенды'),
        ),
        migrations.AddField(
            model_name='rawlayer',
            name='legend_image',
            field=models.ImageField(blank=True, null=True, upload_to='legends', verbose_name='Изображение легенды'),
        ),
    ]
