# Generated by Django 3.2.11 on 2023-11-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20230818_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexchannel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
