version: '3.9'

services:
  geoserver:
    volumes:
      - /mnt/raid1/geoserver-data:/opt/geoserver/data_dir
    environment:
      - HTTP_PROXY_PORT=4814

  nginx:
    ports:
      - "81:80"

  front:
    environment:
      - ROOT_API="http://89.250.84.153:4814/api/"
