version: '3.9'

services:
  geoserver:
    volumes:
      - ../geoserver-data:/opt/geoserver/data_dir

  nginx:
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"

  web:
    volumes:
      - ../geoserver-data:/geoserver_data
