version: '3.9'

services:
  geoserver:
    volumes:
      - ../geoserver-data:/opt/geoserver/data_dir

  nginx:
    ports:
      - "80:80"

  web:
    volumes:
      - ../geoserver-data:/geoserver_data

  front:
    environment:
      - ROOT_API="http://localhost/api/"
