version: '3.9'

volumes:
   geo-db-data:

services:
   db:
      image: kartoza/postgis:${POSTGIS_VERSION_TAG}
      volumes:
         - geo-db-data:/var/lib/postgresql
      ports:
        - ${POSTGRES_PORT}:5432
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
        - FORCE_SSL=TRUE
      restart: on-failure
      healthcheck:
        test: "exit 0"

   geoserver:
      image: kartoza/geoserver:${GS_VERSION}
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
        - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
        - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
        - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
        - INITIAL_MEMORY=${INITIAL_MEMORY}
        - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
      depends_on:
        - db
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3

   nginx:
     image: nginx
     volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
       - ../web/static_root:/static_root
       - ../web/media_root:/media_root
       - ../front/front/dist/:/front:ro
     logging:
       driver: json-file
       options:
         max-size: 200m
         max-file: '10'
     depends_on:
       - geoserver
     ports:
       - "81:80"

   front:
     build:
       context: ../front
       dockerfile: docker/Dockerfile
     volumes:
       - ../front/front/dist/:/front/dist/
     tty: true
     stdin_open: true
     restart: always

   web:
    env_file:
      - ../.env
    expose:
      - 8000
    depends_on:
      - db
    restart: always
    build:
      context: ../web
      dockerfile: docker/Dockerfile
    command: ["start-dev"]
    volumes:
      - ../web:/opt/app
      - ../web/media_root:/opt/app/media_root
      - ../web/static_root:/opt/app/static_root
    tty: true
    stdin_open: true
